name: first workflow

on:
  workflow_dispatch:
  
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: firstJob script
        shell: bash
        run: echo Hello World! This is the first job
      - name: checkout
        uses: action/checkout@v3
      - name: greetings
        id: greetings
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mona de Octocat'
      - name: time
        run: |
          echo "The time of the greeting was at: ${{ steps.greetings.outputs.time }}"

  secondjob:
      runs-on: ubuntu-latest
      steps:
        - name: secondJob script
          shell: bash
          run: |
            echo this the second job
            echo and this is a multi-line script
